version: '3.8'
services:
  backend:
    build:
      context:  ./
      dockerfile: Dockerfile
    container_name: bank-application
    command: ["bee", "run", "-gendoc=true", "-downdoc=true"]
    ports:
      - '5000:5000'
    env_file:
      - .env
